# @package _global_
defaults:
  - dataset: image_dataset
  - architecture: image_architecture
  - tuner: image_tuner
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

package_name: upstage-cv
project_dir: /data/ephemeral/${package_name}
connected_dir: /data/ephemeral/${package_name}
submission_name: submission

seed: 2024

num_labels: 17

split:
  train: train
  val: val
  predict: predict

batch_size: 16

model_type: resnet50
pretrained: pretrained

lr: 0.00001
t_max: 50
eta_min: 0.0000025

monitor: val_MulticlassF1Score
tracking_direction: max
patience: 3
min_delta: 0

devices: -1
accelerator: gpu
strategy: auto
log_every_n_steps: 10
precision: 32
epoch: 100

model_name: Image
dataset_name: UpStageDocs
mode: train

is_tuned: tuned
num_trials: 3
hparams_save_path: ${connected_dir}/hparams/${model_name}/${dataset_name}/${num_trials}_trials
tuned_hparams_path: ${hparams_save_path}/best_params.json

project_name: ${model_name}-${dataset_name}-${mode}
save_detail: model_type_${model_type}-pretrained_${pretrained}
resumed_step: 0
ckpt_path: ${callbacks.model_checkpoint.dirpath}/epoch${epoch}.ckpt

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}